### ISSUE TITLE
Better path config names

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2088]
We don't have currently a clear convention for the config settings that are used to specify path:

* prefix
* store
* pnpm-prefix (used currently for the global packages location)
* lockfile-directory

**Suggestion.** We can suffix every path config with dir:

* [ ] prefix -> dir #2115, #2122
  prefix will continue to work for compatibility with npm's API
  initially we wanted to call it working-dir but 54% of our users voted for dir [on Twitter](https://twitter.com/pnpmjs/status/1188103282662748162)
* [x] store -> store-dir #2118
* [x] pnpm-prefix -> global-dir #2121
* [x] lockfile-directory -> lockfile-dir #2120
* [x] virtual-store-dir ([upcoming config](https://github.com/pnpm/pnpm/issues/2078))

cc @pnpm/collaborators

**Comment by KSXGitHub** [comment]
"workdir" doesn't have hyphen like the rest. I suggest "work-dir".

**Comment by zkochan** [comment]
ok. work-dir or working-dir?

**Comment by ExE-Boss** [comment]
The thing is, `prefix` is inherited from npm.

**Comment by zkochan** [comment]
`prefix` will be an alias but the docs and help will suggest using `--work-dir` or anything else we come up with.

**Comment by aparajita** [comment]
> ok. work-dir or working-dir?

working-dir. That's standard terminology.

**Comment by KSXGitHub** [comment]
> ok. work-dir or working-dir?

Either is fine, but I do prefer "working-dir"

**Comment by zkochan** [comment]
I just discovered that `--prefix` in `npm` has a shorthand `-C`. And `-C` was borrowed from `tar`. 

tar's help prints `-C, --directory=DIR        change to directory DIR`

maybe we could use `--dir` instead of `--working-dir`?

**Comment by KSXGitHub** [comment]
Now I like `--dir` better than `--working-dir`

**Comment by zkochan** [comment]
:ship: [4.2.0-0](https://github.com/pnpm/pnpm/releases/tag/v4.2.0-0)
