### ISSUE TITLE
Reduce the directory nesting

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2521]
When creating the [content-addressable storage](https://github.com/pnpm/pnpm/issues/2470) for pnpm v5, I discovered that reducing the number of directories improves performance a lot.

We have a couple of places where we could reduce the nesting of directories.

- [ ] #2531 In the virtual store directory (`node_modules/.pnpm`), packages are stored inside `<package name>/<package version>`. We may reduce nesting by one directory and store the package at `<package name>@<package version>`. ~Scoped packages also have an additional directory for their scope. We could probably unnest them as well. Like `@<scope>+<name>@<version>`.~
- [x] #2527 In the global store, the package index files (`integrity.json`) are stored in a similar directory structure to the one in the virtual store dir. We could store these files in the CAFS and reduce directory nesting for the package index files.
- [x] #2530 instead of creating a separate subdir for executables in the cafs, just suffix them with something like `-exec`
- [x] #2529 no directory should be created for the different metadata files. (instead of `registry/acorn/index.json` just save it to `registry/acorn.json`).
