### ISSUE TITLE
Use Jest for testing instead of tape

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2858]
- [x] /pnpm/packages/audit - #2862
- [x] /pnpm/packages/package-store a86209b67fccc37c5b017dd9ce61d2b3f9a55789
- [x] /pnpm/packages/cafs #2867
- [x] /pnpm/packages/client https://github.com/pnpm/pnpm/pull/2877
- [x] /pnpm/packages/fetch https://github.com/pnpm/pnpm/pull/2878
- [x] /pnpm/packages/filter-lockfile #2887
- [x] /pnpm/packages/filter-workspace-packages #2887
- [x] /pnpm/packages/find-packages #2887 
- [x] /pnpm/packages/find-workspace-packages #2887 
- [x] /pnpm/packages/dependencies-hierarchy @zkochan
- [x] /pnpm/packages/list @zkochan 
- [x] /pnpm/packages/default-resolver @juanpicado 
- [x] /pnpm/packages/dependency-path @juanpicado 
- [x] /pnpm/packages/config @juanpicado 
- [x] /pnpm/packages/lifecycle @statianzo #2907 
- [x] /pnpm/packages/link-bins @statianzo #2907 
- [x] /pnpm/packages/local-resolver @statianzo #2909
- [x] /pnpm/packages/lockfile-file @statianzo #2909
- [x] /pnpm/packages/lockfile-utils @statianzo #2909
- [x] /pnpm/packages/manifest-utils @statianzo #2913
- [x] /pnpm/packages/matcher @statianzo #2913
- [x] /pnpm/packages/modules-yaml @statianzo #2913
- [x] /pnpm/packages/npm-registry-agent @statianzo #2913
- [x] /pnpm/packages/git-fetcher @juanpicado #2924
- [x] /pnpm/packages/global-bin-dir @juanpicado  #2924
- [x] /pnpm/packages/resolve-dependencies @zkochan
- [x] /pnpm/packages/outdated @juanpicado https://github.com/pnpm/pnpm/pull/2953
- [x] /pnpm/packages/package-bins @juanpicado https://github.com/pnpm/pnpm/pull/2953
- [x] /pnpm/packages/pnpmfile c https://github.com/pnpm/pnpm/pull/2953
- [x] /pnpm/packages/plugin-commands-installation @zkochan #2956
- [x] /pnpm/packages/npm-resolver @zkochan 
- [x] /pnpm/packages/tarball-fetcher @zkochan 
- [x] /pnpm/packages/package-requester @zkochan 
- [x] /pnpm/packages/plugin-commands-publishing @zkochan 
- [x] /pnpm/packages/supi @zkochan #3003
- [x] /pnpm/packages/pnpm @zkochan #3008
- [x] /pnpm/packages/headless @zkochan
- [x] /pnpm/packages/make-dedicated-lockfile @juanpicado
- [x] /pnpm/packages/package-is-installable @juanpicado
- [x] /pnpm/packages/git-resolver @zkochan
- [x] /pnpm/packages/parse-cli-args
- [x] /pnpm/packages/pkgs-graph
- [x] /pnpm/packages/plugin-commands-audit @zkochan #3011
- [x] /pnpm/packages/plugin-commands-import @zkochan #3011
- [x] /pnpm/packages/plugin-commands-listing @zkochan #3011 
- [x] /pnpm/packages/plugin-commands-outdated @zkochan #3011
- [x] /pnpm/packages/plugin-commands-rebuild @zkochan #3011
- [x] /pnpm/packages/plugin-commands-script-runners @zkochan #3011
- [x] /pnpm/packages/plugin-commands-store @zkochan #3011
- [x] /pnpm/packages/prune-lockfile
- [x] /pnpm/packages/read-package-json
- [x] /pnpm/packages/read-project-manifest
- [x] /pnpm/packages/server
- [x] /pnpm/packages/tarball-resolver
- [x] /pnpm/packages/write-project-manifest
- [x] /pnpm/privatePackages/assert-project
- [x] /pnpm/privatePackages/assert-store
- [ ] /pnpm/packages/default-reporter

**Comment by juanpicado** [comment]
Should it has a central config file which each package extend from ?

**Comment by zkochan** [comment]
A single config in the root would be perfect, if possible

Juan Picado <notifications@github.com> ezt írta (időpont: 2020. szept. 14.,
H 20:24):

**Comment by juanpicado** [comment]
I'll give a try 👍  with `/pnpm/packages/audit` and root config, small enough for getting started.

**Comment by juanpicado** [comment]
My next after `cafs` is `client`, `fetch`.

**Comment by juanpicado** [comment]
@zkochan some of the packages in the list do not have test, what do we do ? ~scratch them~? in order to don't create confusion I mean.

**Comment by zkochan** [comment]
delete or strikethrough

**Comment by zkochan** [comment]
Some of the projects have too many tests (like supi), so I suggest to convert them partially at the beginning. So part of the tests will run on jest and some will stay on tape during a transition period.

**Comment by juanpicado** [comment]
@zkochan I updated the list, removed those do not contain `test` folder.
