### ISSUE TITLE
Plug'n'Play

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2902]
### Current state

- A separate CLI tool is availabe to create a `.pnp.js` file from a `pnpm-lock.yaml`: [lockfile-to-pnp](https://github.com/pnpm/pnpm/tree/master/packages/lockfile-to-pnp)
- A setting is available to disable symlinks creation: `symlink=false` (#2900)

### Things to do:

- [x] Add workspace support
- [x] Add bins support #2908
- [x] Make scripts work with pnp #2908
- [x] Add a `node-linker=pnp` setting #2908
- [ ] pnpx should support `.pnp.js`

### Questions

- Should the `.pnp.js` file be committed? if no, can we move it to `node_modules/.pnpm/pnp.js`? - No, it should not. there are parts in the runtime that expects the PnP file to be at the root

**Comment by arcanis** [comment]
> if no, can we move it to `node_modules/.pnpm/pnp.js`?

I'd recommend not to, as there are parts in the runtime that expects the PnP file to be at the root (to support the multi-tree use case, where one project requires files from a separate project).

**Comment by ExE-Boss** [comment]
> - Add a `pnp=true` setting

I’d prefer a `node‑linker = pnp` setting (with the default being `node‑modules`), [like what **Yarn** does](https://yarnpkg.com/configuration/yarnrc#nodeLinker).

**Comment by zkochan** [comment]
@arcanis I am not sure I understand the right way bin commands and scripts should be used with PnP. Seems like Yarn doesn't even create a `node_modules/.bin` directory, so then how do the bins work inside scripts? And how does code like `node index.js` work inside scripts?

I can solve the bins problem easily, by passing some additional options to cmd-shim that will add the `--require=../.pnp.js` argument to node. But how to solve the `node index.js` problem, I am not sure. Maybe by creating a node wrapper.

How does Yarn solve it? Can we use the same libs to solve it in pnpm?

**Comment by ExE-Boss** [comment]
@zkochan
Probably by setting the `NODE_OPTIONS` environment variable so that it contains `‑‑require=/path/to/.pnp.js`

**Comment by zkochan** [comment]
@ExE-Boss yes, setting `NODE_OPTIONS` seems to work. Thanks.

**Comment by ExE-Boss** [comment]
As for the bins, that’s probably done by passing the commands as `builtins` to [`@yarnpkg/shell`](https://www.npmjs.com/package/@yarnpkg/shell).

**Comment by zkochan** [comment]
We can keep generating the bins with cmd-shim. Setting NODE_OPTIONS fixes them as well.

**Comment by arcanis** [comment]
Yes, we set `NODE_OPTIONS` before spawning the scripts and binaries 👍

> As for the bins, that’s probably done by passing the commands as `builtins` to [`@yarnpkg/shell`](https://www.npmjs.com/package/@yarnpkg/shell).

No, we only use NODE_OPTIONS. Note that in our case, since we keep packages within their zip archives, we don't allow non-JS scripts within the `bin` field (which is a good practice anyway, since that wouldn't be portable).

**Comment by zkochan** [comment]
The PR is progress but seems like it works, just need to add tests.

I published the changes, you can install it with `pnpm i -g pnpm@dev`

set `node-linker=pnp` and optionally `symlinks=false`.

**Comment by zkochan** [comment]
Plug'n'Play published with [pnpm v5.9.0](https://github.com/pnpm/pnpm/releases/tag/v5.9.0)

**Comment by zkochan** [comment]
I am looking into using PnP in a more optimal way with pnpm. It will require some changes to the plug'n'play code as well. Ideally, we should not create hard links from the content-addressable store to the virtual store at `node_modules/.pnpm`. PnP should be able to read the modules directly from the content-addressable store.

Seems like there are 2 ways this can be done. 

1. we can extend [resolveRequest()](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-pnp/sources/loader/makeApi.ts#L783) to read the package index from the store and map the package path to the file in the store. Maybe we can add some new field, like `packageIndex` that would trigger this functionality.
2. we can add a new fs layer that would hide the manipulations with the store from the resolver. That's how manipulation with zip are implemented. https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-pnp/sources/loader/_entryPoint.ts#L30-L37

I am trying the first technique now as it seems easier for me, with my bad knowledge of Yarn's codebase.

This is an example of an index file that I was mentioning: https://raw.githubusercontent.com/pnpm/sample-project/master/pnpm-store/v3/files/34/f5049ce1ecdf2b0649af3ef24e45ed35416d91-index.json

the checksums should be converted to hex and then it is a path to the actual file in the store.

**Comment by ExE-Boss** [comment]
Also, **pnpm** should always use `.pnp.cjs` from the start, like what **Yarn 3** will be doing: <https://github.com/yarnpkg/berry/issues/1406>

**Comment by zkochan** [comment]
What does the `.cjs` extension mean?

**Comment by ExE-Boss** [comment]
@zkochan
It means that the file is always parsed and evaluated as a **CommonJS** module, even when `package.json` has `{ "type": "module" }`, which causes all `.js` files to be parsed and evaluated as **ECMAScript** modules:
- <https://nodejs.org/api/packages.html#packages_determining_module_system>

**Comment by MKRhere** [comment]
I want to say, https://github.com/pnpm/pnpm/releases/tag/v5.9.0 is the only place on the internet I could find that says `.pnp.js` has to be required with `node --require .pnp.js index.js` so your PnP project works (kudos to @zkochan's release notes).

yarnpkg.com has a relatively passing mention to "Call your scripts through `yarn node` rather than `node`"; for some reason perhaps it's super obvious for everyone else involved, but there's no 1-2-3 instruction on how to start using PnP even after reading lots of material on yarn docs.

From my understanding, pnpm support for PnP is still in development (?) given the issue is open (it still generates hardlinks in `node_modules/.pnpm`), and may include a node wrapper (like `pnpm node` === `node --require ./.pnp.js`?) later (however, `pnpm run` commands already seem patched to require `.pnp.js`).

I hope when we're confident with pnpm's implementation, the "getting started with PnP" docs are better on our side 😅

> Seems like there are 2 ways this can be done.

Patching `resolveRequest` seems to be the starting point to me as well.

The intention of yarn's fake FS layer does not seem to be to hide store manipulations from the resolver, but to enable `require`ing files from the package path (like `require("lib/path/to/file")` when the file does not actually exist on disk and is within the package zip (yarn PnP never unpackages them).

If I've understood correct, pnpm universally unpackages all package zips into a content-addressable store, so we might not need to do fs patching (? if my understanding is wrong, do point it out :) )

**Comment by zkochan** [comment]
> From my understanding, pnpm support for PnP is still in development (?) given the issue is open

Actually, I think this issue is actually done. Of course, we can improve how we use PnP but PnP support is already implemented and may be used.

For the docs, currently, we don't have a lot of docs about PnP because we usually just reference [Yarns page](https://yarnpkg.com/features/pnp). I don't have objections to adding a dedicated page to our docs about PnP.

> If I've understood correct, pnpm universally unpackages all package zips into a content-addressable store, so we might not need to do fs patching (? if my understanding is wrong, do point it out :) )

You are correct but we probably still need to patch things like `fs.readdir`.

In any case, I don't work on this currently because it appeared to be pretty hard and time-consuming. Linking packages from the Yarn monorepo to the pnpm monorepo appeared to be an impossible task. Then I decided to copy the needed packages to the pnpm monorepo but I wasn't able to configure them yet (the branch is [improve-pnp](https://github.com/pnpm/pnpm/tree/improved-pnp)).

**Comment by MKRhere** [comment]
> Actually, I think this issue is actually done.
> PnP support is already implemented and may be used.

Of course, I plan to start using it in the current state after experimenting more. Upon thinking further, it seems we still need the hardlinked store because pnpm 5+'s content-addressable store doesn't have the package's file tree like you'd normally have. So that might actually be okay (?)

> I don't have objections to adding a dedicated page to our docs about PnP.

In that case, if/once I understand PnP and its implications better, I'll try to put some effort into a PR :)

**Comment by arcanis** [comment]
> In that case, if/once I understand PnP and its implications better, I'll try to put some effort into a PR :)

If you care to help improve Yarn as well, we're more than happy to receive PRs! 🙂 This page was written by someone with far too much context on PnP (me 😛), it would certainly benefit from a review by someone who just learned about it.

**Comment by MKRhere** [comment]
@arcanis Haha, I have far less context on yarn itself; but I'll try if I get the time!

**Comment by arcanis** [comment]
I've added a new section about [initializing PnP](https://yarnpkg.com/features/pnp#initializing-pnp), does it look better? I added it after the first two sections though since it requires knowledge of what the `.pnp.cjs` file is in the first place 🤔

**Comment by MKRhere** [comment]
@arcanis New addition is good, also explains `require('./.pnp.cjs').setup()` which was previously unknown to me :smile:
