### ISSUE TITLE
Trying pnpm on big and popular Node projects

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#532]
To find potential issues, I decided to clone the most popular Node packages and use pnpm to install their dependencies. The installation should be successful and the tests should pass.

I started with webpack and already found an easy to fix issue (webpack is not accessible in the dependencies that use it as a peer dep).

This is very easy to do. If someone would love to help me with it, post your observations here

* [x] - [webpack project](https://github.com/webpack/webpack)
* [x] - create-react-app
* [ ] - [rxjs](https://github.com/ReactiveX/rxjs) - fails on postinstall #535
* [x] - [black-screen](https://github.com/shockone/black-screen) - found and fixed #534 in v0.48.0
* [x] - [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) - does not work #79
* [x] - [typescript](https://github.com/Microsoft/TypeScript)
* [x] - [Angular 2 Quickstart](https://github.com/angular/quickstart)

Findings:
* frequently packages are using dependencies which aren't specified neither as dependencies nor as peer dependencies. They work only because of the flat dependency tree created by npm@3

**Comment by andreypopp** [comment]
Tried pnpm 0.47.0 with CRA and got a few failures first related to eslint plugins and then webpack wasn't able to find react, react-dom.

**Comment by zkochan** [comment]
Are you on Windows? There was an error I fixed in v0.47.1 that caused issues in packages like eslint.

And thanks!

**Comment by andreypopp** [comment]
Nope, macOS. Let me try 0.47.1.

**Comment by andreypopp** [comment]
Still no luck with eslint related packages. Also second run of pnpm produces some weird output with `undefined` instead of packages' versions:
<img width="963" alt="screen shot 2017-01-11 at 00 54 56" src="https://cloud.githubusercontent.com/assets/30594/21826458/9b378bbc-d798-11e6-9dda-2d39c4bd43b7.png">

Repro:
```
% create-react-app myapp
% cd myapp
% rm -rf node_modules
% pnpm install
% npm start
```
 After I install eslint related packages manually it starts working! And btw `node_modules` weights just `132MB` (!!!) — that's very good (see [stats](https://twitter.com/nicdex/status/818606636919095296) for npm/yarn).

**Comment by zkochan** [comment]
Cool! I'll look into it after fixing the webpack issue

Also we use links currently, so there will be some confusion around disk usage. It will look like the packages are using space both in the global store and locally in the project's node_modules folder. However, they use the same space. 

The disk space savings will grow exponentially! The packages of 10 react apps will use the roughly the same space as the packages of 1 react app

**Comment by birchb** [comment]
Initializing a new vue project using vue-cli results in the following error:

```
This dependency was not found:

* vue-hot-reload-api in ./src/App.vue, ./~/.registry.npmjs.org/vue-loader/11.3.4/~/vue-loader/lib/template-compiler?{"id":"data-v-59778c66"}!./~/.registry.npmjs.org/vue-loader/11.3.4/~/vue-loader/lib/selector.js?type=template&index=0!./src/App.vue and 2 others

To install it, you can run: npm install --save vue-hot-reload-api
```

After running:

`pnpm install --save vue-hot-reload-api`

the dev server complies and loads correct.

**Comment by zkochan** [comment]
hey @birchb, I am sorry for not reacting to your problem. I somehow missed your post.

I created a separate issue for this https://github.com/pnpm/pnpm/issues/831

**Comment by patricksile** [comment]
Hi, @zkochan Please **VueJS** and **Angular** won't work with `pnpm` I hope I will find a solution soon, or if someone has one I will be happy to see it. Thanks

**Comment by zkochan** [comment]
You can read about workarounds for Angular here: https://github.com/pnpm/pnpm/issues/1260

For Vuejs you may try the shamefully-flatten config as well

**Comment by dandv** [comment]
[apollo-server](https://github.com/apollographql/apollo-server/issues/2151) doesn't work either.

**Comment by xialvjun** [comment]
> [apollo-server](https://github.com/apollographql/apollo-server/issues/2151) doesn't work either.

I used to do not know why pnpm give the api `--shamefully-flatten` such a name. Now I got it.

**The pnpm choose the right way, but the community choose the easy way.**

ㄟ( ▔, ▔ )ㄏ

(╯‵□′)╯︵┻━┻

**Comment by xialvjun** [comment]
@zkochan please reopen this issue. Make this issue just like the Top 1 bug in linux's bug list: Windows.

**Comment by zkochan** [comment]
Issues are not for documentation. We have a documentation website at https://pnpm.js.org/en/
If some workarounds/recipes need to be documented, that's the place
