### ISSUE TITLE
Catalogs Tracking Issue

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#7072]
This is a tracking issue for the implementation of [_RFC: Catalogs — Shareable dependency version specifiers_](https://github.com/pnpm/rfcs/pull/1). All pull requests and commits related to the initial implementation of this feature will reference this issue number.

## Tasks

- [x] Support the `catalog:` and `catalog:default` specifiers during installation.
- [x] Support `catalog:<name>` specifiers during installation.
- [x] ~~There will likely need to be a `lockfileVersion` increase in the `pnpm-lock.yaml` file.~~
  - **Update**: This won't be required after all.
- [x] Make `pnpm outdated` work. I should be able to run `pnpm outdated` and it should be able to list all the packages in my `pnpm-workspace.yaml` file that are outdated
  - https://github.com/pnpm/pnpm/pull/8304
- [x] Show an error for recursive catalog references.
- [x] Add docs. (Done at https://pnpm.io/catalogs)
- [x] https://github.com/pnpm/pnpm/issues/8640
- [x] https://github.com/pnpm/pnpm/issues/8641

### Improvements

These would be good to have, but not required.

- [x] Support the `catalog:` protocol for `pnpm.overrides`. 
- [x] Persist comments and white-space when updating `pnpm-workspace.yaml`. We don't do this for `package.yaml` either, but hopefully we can carry over whatever solution lands there.
- [ ] https://github.com/pnpm/pnpm/issues/8245
- [ ] Allow users to create a best-effort default catalog. We could consider an internal `pnpm catalog migrate` command or an external `pnpm dlx @pnpm/catalog-migrate` command.
- [x] Test common automated dependency mechanisms such as Dependabot and Mend Renovate to track whether they can support catalog updates.
- [x] https://github.com/pnpm/pnpm/issues/8642

## Tests

- [x] Changing a catalog entry in `pnpm-workspace.yaml` causes the lock file to not be up to date.
- [x] Catalog specifiers error out if used by external dependencies.

## Rollout

- [x] Update docs to explain how the catalog works.
- [x] ~~Consider a more publicly facing announcement that explains what problems catalogs solve.~~
  - The docs site should suffice. https://pnpm.io/catalogs

## PRs

Merged into `main`:

- https://github.com/pnpm/pnpm/pull/8205
- https://github.com/pnpm/pnpm/pull/8213
- https://github.com/pnpm/pnpm/pull/8214
- https://github.com/pnpm/pnpm/pull/8215

Staged onto feature branch:

- https://github.com/pnpm/pnpm/pull/8026
- https://github.com/pnpm/pnpm/pull/8123
- https://github.com/pnpm/pnpm/pull/8124
- https://github.com/pnpm/pnpm/pull/8125
- https://github.com/pnpm/pnpm/pull/8225
- https://github.com/pnpm/pnpm/pull/8221

Merged into `main` after feature branch merged

- https://github.com/pnpm/pnpm/pull/8254
- https://github.com/pnpm/pnpm/pull/8255
- https://github.com/pnpm/pnpm/pull/8259
- https://github.com/pnpm/pnpm/pull/8281
- https://github.com/pnpm/pnpm/pull/8285
- https://github.com/pnpm/pnpm/pull/8286
- https://github.com/pnpm/pnpm/pull/8304

**Comment by JasonMan34** [comment]
A question from someone who has not contributed to pnpm in the past and is very excited for this feature

How would I go about contributing to this, if I can?

**Comment by gluxon** [comment]
Hey @JasonMan34, thanks for the offer to help! I'm focusing on this more extensively over the next few days. I'll give a heads up here if there are any tasks that could use assistance.

- If you'd like to get your feet wet with the pnpm codebase, feel free to take a look at the currently [open issues](https://github.com/pnpm/pnpm/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22). Fixing a small bug would be a good opportunity to set up the repo, get it compiling, and open a PR.
- I'm certain we'll need help testing the catalogs feature. I'll also give a heads up when we're ready for that.

Would you want to help code review? Extra eyes always helps code quality.

**Comment by JasonMan34** [comment]
> Would you want to help code review? Extra eyes always helps code quality.

Sure absolutely, glad to help any way I can :)

**Comment by darkbasic** [comment]
> Maintaining version consistency across a monorepo is a painful chore.

This is indeed the main reason why I switched [accounts.js](https://github.com/accounts-js/accounts) to yarn v4. The integrated `upgrade-interactive` plugin makes it an easy job to ensure that each and every instance of a dependency stays at the same version (the other reason is the fact that it integrates a task runner).

**Comment by taozhou-glean** [comment]
anywhere to see the progress on this or any UFG issues, excited to see this and hope it can land soon!

**Comment by NullVoxPopuli** [comment]
for anyone watching this, I happened to make a similar utility before learning about catalogs: https://github.com/NullVoxPopuli/defrag

difference tho is that you don't change anything about your package.json entries.

**Comment by zkochan** [comment]
> There will likely need to be a lockfileVersion increase in the pnpm-lock.yaml file.

If this is the case, it would be best to ship it before v9 is out.

**Comment by yyx990803** [comment]
I was pretty excited about this when I heard about it from last year's ViteConf as this is something I've wanted in vuejs/core for a while. Good to see that there are finally movements in https://github.com/pnpm/pnpm/pull/8221 and https://github.com/pnpm/pnpm/pull/8225!

**Comment by gluxon** [comment]
> @gluxon At version 9.5.0-beta.0, `pnpm update --latest` still replaces `catalog:` with versions. Do you plan to fix this?

@KSXGitHub That's a good catch. I can fix that.

**Comment by MoazAlkharfan** [comment]
Hey,
Great feature by the way.

I'm trying to add the `@types/react` into the catalog but it seems it's not matching quoted values because of yaml rules
`Plain value cannot start with reserved character @`
and I'm getting the following error when running `pnpm i`

```
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @types/react@catalog: isn't supported by any available resolver.
```

```yaml
# ./pnpm-workspaces.yaml
packages:
  # packages....

catalogs:
  "@types/react": ^18.2.46 # double quotes don't match
  '@types/react': ^18.2.46 # single quotes don't match either
  # other...
```

**Comment by KSXGitHub** [comment]
@MoazAlkharfan Try changing `catalogs` (plural) in your `pnpm-workspace.yaml` into `catalog` (singular)

**Comment by MoazAlkharfan** [comment]
@KSXGitHub Sorry i thought this feature was supported in pnpm version `9.4.0` i updated into `9.5.0` and it's working fine.

**Comment by jakeleventhal** [comment]
There should be a task to make `pnpm outdated` work. I should be able to run `pnpm outdated` and it should be able to list all the packages in my pnpm-workspace.yaml file that are outdated

**Comment by zkochan** [comment]
Related issue: https://github.com/pnpm/pnpm/issues/8297

**Comment by tingtingdisco** [comment]
I am using pnpm v9.10.0, and I can use the catalog protocol to specify versions in my `pnpm.overrides`. 

Is it official?

**Comment by zkochan** [comment]
@tingtingdisco it is documented in the docs: https://pnpm.io/catalogs

**Comment by jakeleventhal** [comment]
> There should be a task to make `pnpm outdated` work. I should be able to run `pnpm outdated` and it should be able to list all the packages in my pnpm-workspace.yaml file that are outdated

Is there an issue tracking this? I don't see this in the tasks in the main issue description.

**Comment by zkochan** [comment]
@jakeleventhal `pnpm outdated` added to the tasks

**Comment by danielbayley** [comment]
Would a cleaner solution not be to just list shared dependencies in the root `package.json`/`.yaml`, and provide a way to reference them from sub`packages/*`? @zkochan @gluxon

**Comment by sergioflores-j** [comment]
I've found 2 bugs with catalogs when using the setting `recursive-install` set to false. 
Not sure if they are by design or not, but here is a repo with reproduction steps:

https://github.com/sergioflores-j/pnpm-bugs-repro

If needed I can create separate issues for them! :D

**Comment by zkochan** [comment]
> Would a cleaner solution not be to just list shared dependencies in the root package.json/.yaml, and provide a way to reference them from subpackages/*? @zkochan @gluxon

This feature isn't in the discussion phase. We had a [RFC](https://github.com/pnpm/rfcs/pull/1) with a good amount of feedback. What you suggest isn't a better alternative because then you'd have all the shared dependencies installed at the root level and each project in the monorepo would be able to require those dependencies, even if they are not included in their own `package.json`.

@sergioflores-j create a separate issue, please.

**Comment by gluxon** [comment]
> > There should be a task to make `pnpm outdated` work. I should be able to run `pnpm outdated` and it should be able to list all the packages in my pnpm-workspace.yaml file that are outdated
> 
> Is there an issue tracking this? I don't see this in the tasks in the main issue description.

This should be fixed! Does it now work as expected @jakeleventhal?

- https://github.com/pnpm/pnpm/pull/8304

If not, feel free to open a new issue and tag me to keep this tracking issue less noisy.

**Comment by gluxon** [comment]
> I've found 2 bugs with catalogs when using the setting `recursive-install` set to false. Not sure if they are by design or not, but here is a repo with reproduction steps:
> 
> https://github.com/sergioflores-j/pnpm-bugs-repro
> 
> If needed I can create separate issues for them! :D

Thanks for finding these bugs @sergioflores-j. Appreciate the clear reproduction steps. I've created issues for them so I can assign myself and track a fix. 

- https://github.com/pnpm/pnpm/issues/8639
- https://github.com/pnpm/pnpm/issues/8638

**Comment by jakeleventhal** [comment]
It appears to work @gluxon :)

Slightly off-topic, is there a vs code extension that supports something like this screenshot where when you hover over a package version, it shows the latest version? would be nice to have this inside the pnpm-workspace.yaml file
<img width="577" alt="Screenshot 2024-10-14 at 7 32 18 AM" src="https://github.com/user-attachments/assets/d2c16f1c-4077-41b1-a157-0188f2e2fdfd">

**Comment by zkochan** [comment]
@jakeleventhal there is the [pnpm-catalog-lens](https://marketplace.visualstudio.com/items?itemName=antfu.pnpm-catalog-lens) by @antfu

**Comment by jakeleventhal** [comment]
This is a nice project, but not exactly what i was referring to. I'll open a feature request there. Thank you!

**Comment by zkochan** [comment]
I'd add one more feature request for catalogs, loading catalogs from [configurational dependencies](https://pnpm.io/config-dependencies). This would allow to share catalogs between repositories.

**Comment by btea** [comment]
@gluxon Is there any way we can solve this situation? https://github.com/pnpm/pnpm/issues/8999

**Comment by gluxon** [comment]
Hey @btea, I'll respond on the issue you linked. Feel free to `@`-mention me on separate issues in the future.

**Comment by zkochan** [comment]
> @zkochan Let's do it! Loading catalogs from configurational dependencies would be a really powerful feature since it allows tools to recommend versions that consumers can follow.

Just verified that the new "updateConfig" hook, which will ship in pnpm v10.8, works for catalogs: https://github.com/pnpm/pnpm/pull/9367

**Comment by ghoullier** [comment]
Can you consider take a loot at this one ? https://github.com/pnpm/pnpm/issues/8718

**Comment by ValentinGurkov** [comment]
Do the pnpm completions support catalog-related arguments?

**Comment by jinghaihan** [comment]
pnpm add replaces workspace fields with `catalog:name` when re-adding catalog dependencies, I can still reproduce this issue in the latest version `v10.21.0`.  Link issue [#10123](https://github.com/pnpm/pnpm/issues/10123).

**This may not seem like a major issue, but many third-party CLIs do not check whether a dependency already exists and simply run `pnpm add`, which forces us to avoid using the `catalog:` protocol for those dependencies.**

Such as

```json
{
  "dependencies": {
    "foo": "catalog:bar"
  }
}
```

```yaml
catalogs:
  bar:
    foo: ^1.0.0
```

Run pnpm add foo again.

```json
{
  "dependencies": {
    "foo": "catalog:bar"
  }
}
```

```yaml
catalogs:
  bar:
    foo: catalog:bar
```
